spring.application.name=confeitaria.web

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/confeitaria-web
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${API_SECRET}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username={MAIL_USERNAME}
spring.mail.password={MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true



#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.generate-ddl=true